#!/bin/bash

# Customize these environment variables for your own installation.
export AUTHSERVER=https://auth.fullstack.cash
export APISERVER=https://api.fullstack.cash/v5/
export FULLSTACKLOGIN=bch-ipfs@bchtest.net
export FULLSTACKPASS=bchoveripfs

# Ports
export PORT=5700 # REST API
export IPFS_TCP_PORT=5701 # IPSF TCP Port
export IPFS_WS_PORT=5701 # IPFS WS Port

export ENABLE_CIRCUIT_RELAY=1

export SVC_ENV=production
npm start

