# Start the service with the command 'docker-compose up -d'

version: '3.9'

services:
  mongo-bch-service:
    image: mongo:4.2.0
    container_name: mongo-bch-service
    ports:
      - '5557:27017' # <host port>:<container port>
    volumes:
      - ../data/mongodb:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  ipfs-bch-wallet-service:
    build: .
    #image: christroutner/ipfs-service-provider:v5.0.1
    container_name: ipfs-bch-wallet-service
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    #mem_limit: 1500mb
    links:
      - mongo-bch-service
    ports:
      - '5032:5032' # <host port>:<container port>
      - '5668:5668'
      - '5669:5669'
    volumes:
      - ../data/ipfsdata:/home/safeuser/ipfs-bch-wallet-service/.ipfsdata
      - ./start-production.sh:/home/safeuser/ipfs-bch-wallet-service/start-production.sh
    restart: always
